language: java

jdk: openjdk10

before_install:
  - chmod +x gradlew
  
script:
  - ./gradlew check jacocoTestCoverageVerification

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

after_success:
  - ./gradlew jacocoTestReport coveralls

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: OPQCioSHNjpc0R74J37jlXBiDZvHpVLbmZzAyF5Lhv/sNiCY6bMc6lV+V3ojopJBzqS+sg+csB4qoBAxi2wInqXOTSplFusXz98gsbiLzgO/VFuKkez9FygXiJLJrPSNn+fSME/sfo44dy2oGrjd8IVOSbQObd9OkLBRlyvQcirXkpDob12RgkvMq091vReDXmPeV3eApRFbaI+WSks/i7OloBga2/B8CdFzrgFkjDHt9JIquiR1csf5iQ7tY1sIDky9vhN935N5oKHTk+pbFJRndlwTJRCIEpOidc+9xZTF0cIedgjbIAMRC3sxI9ApV5jyh8lbqgwnWd0+Kvvfs+305vYTBaCxVYATHB3zqxtZYpCgQTJcWhnSYHmt1KzdkBhueElinmm91cxuNL6rCIuJbjRLBPo7ZkzI0Yk98w0tNKeLj3Xt+bERiYrWPPDkR1EnYThXdKGnTpgSNbsEibf8IabCBxcRU/xYnRzKhWX5Ais224cJiTYeQX2gX51rcW9pBEMhrC9ejjAs5wUw+kuo6sn3mXi1kRI+UHJ733vKGYlZOkxvL0hjqytkhe76Vop2He7IFxjMWUCK1/wqfI5vr0KKspzthabHL1CU7F+AYx4m3Tong6v/0kQ8smauF5LGZPI+1DTe8TIYvqRSSWcWUbVluUBdfJHXA/pQyPw=
    file_glob: true
    file: "build/libs/*.jar"
    on:
      tags: true

  - provider: script
    skip_cleanup: true
    script: ./gradlew bintrayUpload
    on:
      tags: true
